
services:
  app:
    container_name: "my_service"
    build:
      context: .
      args:
        VITE_WEB_PORT: "8000"
        VITE_API_BASE_URL: "/"
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - /data/log:/workspace/log
